# Generated by Django 4.2.1 on 2023-06-05 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_remove_demo_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='speed',
        ),
    ]
